version: 2
jobs:
  build:
    working_directory: /go/src/github.com/raintank/tsdb-gw
    docker:
      - image: circleci/golang:1.12.3
    steps:
      - checkout
      - run: scripts/build.sh
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    working_directory: /go/src/github.com/raintank/tsdb-gw
    docker:
      - image: circleci/golang:1.12.3
    steps:
      - checkout
      - run: go test -v -race ./...

  qa:
    working_directory: /go/src/github.com/raintank/tsdb-gw
    docker:
      - image: circleci/golang:1.12.3
    steps:
      - checkout
      - run: scripts/qa/gofmt.sh
      - run: scripts/qa/ineffassign.sh
      - run: scripts/qa/misspell.sh
      - run: scripts/qa/gitignore.sh
      - run: scripts/qa/unused.sh
      - run: scripts/qa/vendor.sh
      - run: scripts/qa/vet-high-confidence.sh

  deploy:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: bundle install
      - run: scripts/build_docker.sh
      - run: scripts/package.sh
      - store_artifacts:
          path: build
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scripts/deploy.sh
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              scripts/deploy_docker.sh
            fi

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test
      - qa
      - deploy:
          requires:
            - build
            - test
            - qa
