version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: /home/circleci/.go_workspace/src/github.com/raintank/tsdb-gw
    parallelism: 1
    shell: /bin/sh
    environment:
      GOPATH: /home/circleci/.go_workspace
      GODIST: go1.8.1.linux-amd64.tar.gz
    steps:
    - checkout
    - run:
        name: prepare build env
        command: |
          sudo apt-get update
          sudo apt-get install -y curl git bundler rpm
          mkdir -p download
          test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf download/$GODIST
          sudo ln -s /usr/local/go/bin/* /bin/
    - run:
        name: run tests
        command: |
          scripts/vendor_health.sh
          scripts/build.sh
          scripts/build_docker.sh
          go test -v -race $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
    - run:
        name: build package
        command: |
          bundle install
          scripts/package.sh
    - store_artifacts:
        path: build
