---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: ingester
  spec:
    replicas: 1
    minReadySeconds: 60
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
  
    template:
      metadata:
        labels:
          app: cortex-gw
      spec:
        containers:
        - name: cortex-gw
          image: raintank/cortex-gw
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1